[unstable]
profile-rustflags = true

[profile.test]
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
rustflags = ["-C", "target-cpu=native"]

[profile.deployment]
rustflags = [
    "-C", "target-cpu=native",
    #"-C", "target-feature=+crt-static"
]

[build]
incremental = true

[alias]
dev = "run -p pipe-bolt-daemon --features dev"
dev-check = "check --workspace --features dev"
dev-test  = "test --workspace --features dev"
deploy = "build --profile deployment"